# Delete's AWS images
# this post has way to get images. 
# call with: ansible-playbook terminate-ec2.yml
# requires that you have boto installed and a ~/.boto file installed.
# the .boto file should have the following env variables: 
# aws_access_key_id = ABCD...
# aws_secret_access_key = ZYXWVUTSR..

- hosts: ec2
  gather_facts: True
  connection: local
  vars: 
    - region: 'eu-west-1'
  tasks:
    - name: Gather EC2 facts
      local_action: ec2_facts

    - debug: var=hostvars[inventory_hostname]
    - debug: msg="{{ hostvars[inventory_hostname]['ec2_id'] }}"

    - name: Terminate instances 
      local_action: ec2
        state='absent'
        instance_ids='{{ ec2_id }}'
        region='{{ region }}'
        wait=True
      #with_items: hostvars[inventory_hostname]['ec2_id']
